### ISSUE TITLE
WIFI , HTTP , MQTT Blocky needed ! 

### ISSUE THREAD

**Issue by tomcasa** [wireless-tag-com/8ms-esp32#10]
I have received my WT32-SC01 Board. 

I can't find the WIFI and others mandatory instruction needed for my project. 

![image](https://user-images.githubusercontent.com/5180491/157729588-d608dd42-0ede-4b18-895b-c4fcd2d22bf1.png)

Only the basic logic and GUI oriented blocks are present on https://8ms.xyz/ workbench  

![image](https://user-images.githubusercontent.com/5180491/157729944-c53e8800-f7de-44d7-9a0e-b7277de2f21a.png)

I am sorry but I need some support to be able to understand what is going wrong.

**Comment by shukewt** [comment]
We decided to offer reliable blockly function only,so these code may be remastered in couple of weeks.

**Comment by tomcasa** [comment]
@shukewt : 
Thanks a lot for your work. This will be very appreciated  !!

**Comment by M4rv-dev** [comment]
Any update regarding the "Base peripherals" tab? I'm trying to develop some R485 wall switch base on ZX3D95CE01S-AR-4848. I am using the 8ms.xyz platform and don't know how to proceed with the RS485 protocol there.
