### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by HuaTianSoft** [wireless-tag-com/8ms-esp32#6]
环境配置应该是没问题的, 我编译IDF下的例程并未出错.
以下是编译错误日志:

[2/3] Linking CXX executable lvgl-demo.elf
FAILED: lvgl-demo.elf 
cmd.exe /C "cd . && H:\ESP32_IDF\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin\xtensa-esp32s2-elf-g++.exe  -mlongcalls   @CMakeFiles\lvgl-demo.elf.rsp  -o lvgl-demo.elf  && cd ."h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj): unsupported relocation type 0x3b    
../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.back_light_ctrl+0x0): undefined reference to `st7796s_enable_backlight'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.lv_8ms_test+0x8): undefined reference to `ESP_EFUSE_MAC_FACTORY'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.lv_8ms_test+0x30): undefined reference to `esp_efuse_read_field_blob'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.lv_8ms_test+0x34): undefined reference to `esp_aes_init'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.lv_8ms_test+0x38): undefined reference to `esp_aes_setkey'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj):(.literal.lv_8ms_test+0x3c): undefined reference to `esp_aes_crypt_ecb'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj): in function `back_light_ctrl':
lv_8ms.c:(.text.back_light_ctrl+0x5): undefined reference to `st7796s_enable_backlight'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj): in function `logo_handle_task':
lv_8ms.c:(.text.logo_handle_task+0x8a): undefined reference to `st7796s_enable_backlight'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: ../components/lvgl/liblvgl.a(lv_8ms.c.obj): in function `lv_8ms_test':
lv_8ms.c:(.text.lv_8ms_test+0x1d): undefined reference to `esp_efuse_read_field_blob'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: lv_8ms.c:(.text.lv_8ms_test+0xa8): undefined reference to `esp_aes_init'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: lv_8ms.c:(.text.lv_8ms_test+0xc2): undefined reference to `esp_aes_setkey'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: lv_8ms.c:(.text.lv_8ms_test+0xd2): undefined reference to `esp_aes_crypt_ecb'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: lv_8ms.c:(.text.lv_8ms_test+0x106): undefined reference to `esp_efuse_read_field_blob'
h:/esp32_idf/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: final link failed: bad value
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
终端进程“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja ”已终止，退出代码: 1。

**Comment by HuaTianSoft** [comment]
折腾好几天, 确定是liblvgl.a的问题, 请贵司考虑开源该库源代码.

**Comment by Alex-Beh** [comment]
@shukewt @HuaTianSoft 请问最终解决了不？
