### ISSUE TITLE
Where is the files /gslx680/touch_data_handle.c   and gslx680/tp_handle.c

### ISSUE THREAD

**Issue by codewise-nicolas** [wireless-tag-com/8ms-esp32#7]
I cannot seem to find the files 
```
list(APPEND SOURCES "./qmsd_tp/gslx680/touch_data_handle.c")
list(APPEND SOURCES "./qmsd_tp/gslx680/tp_handle.c")
```
needed for the WT32-86

Where are they ?

Thank you.

**Comment by uldara1** [comment]
@codewise-nicolas hello have it work with touch yet ?

**Comment by codewise-nicolas** [comment]
Yes, but it had to be reversed engineered. The files in question are still missing from the repo.

**Comment by uldara1** [comment]
Could you share your code that work with touch sensor? 
Thank

**Comment by fvanroie** [comment]
It seems Wireless-Tag only releases header files and **pre-compiled** libraries...
No `.c` driver files are on the repo and no reply to this request for 2 months now 😞 

@[codewise-nicolas](https://github.com/codewise-nicolas) Did you try asking a Wireless-Tech representative?
@[uldara1](https://github.com/uldara1) We have created a custom driver which can be found at https://github.com/arovak/GSL2038

**Comment by codewise-nicolas** [comment]
I have not, I had hoped since they were using Github they would be reading their emails and issues. 
They keep making commits to the repo even as late as a day ago.

@shukewt, @alan-wt  can either of you please respond.

**Comment by uldara1** [comment]
@fvanroie @codewise-nicolas @shukewt currenly i can program this module with arduino

https://user-images.githubusercontent.com/22394956/161015075-da115161-f650-4cc7-923d-9978474b09b1.MOV
https://user-images.githubusercontent.com/22394956/161015145-29dafc59-044a-4b01-9bab-c5a48569c250.MOV

**Comment by uldara1** [comment]
@poky do you have this board yet ?

**Comment by poky** [comment]
> @poky do you have this board yet ?

Yes, I do, trying to write some code with LVGL
So I found this official repo, too bad it's all compiled into .a, nothing I can customized for it.

**Comment by uldara1** [comment]
@poky 
Hi pls check attached file
[ESP32_S2_LVGL_LovyanGFX.zip](https://github.com/wireless-tag-com/8ms-esp32/files/8692550/ESP32_S2_LVGL_LovyanGFX.zip)

**Comment by poky** [comment]
> @poky Hi pls check attached file [ESP32_S2_LVGL_LovyanGFX.zip](https://github.com/wireless-tag-com/8ms-esp32/files/8692550/ESP32_S2_LVGL_LovyanGFX.zip)
> 
> this code used with Arduino IDE

Thanks! BTW, which version of LVGL are you using?

**Comment by uldara1** [comment]
@poky the lasted version of lvgl

**Comment by poky** [comment]
> @poky the lastest version of lvgl

Thanks! I have it running, but I can't get the touch to work, do I need to calibrate before use? Or other config for the touch

![358777](https://user-images.githubusercontent.com/138415/168457773-f74dae7f-f474-4a5b-a25d-21d2595c8181.jpg)

**Comment by uldara1** [comment]
@poky the code should work with touch pls check your touch cable

**Comment by strange-v** [comment]
Here is a fully functional example of using LVGL 8.2 with LovyanGFX graphic library and PlatformIO, it is partially based on @uldara1's UI code.

https://github.com/strange-v/WT-86-32-3ZW1_LVGL

https://user-images.githubusercontent.com/3875529/173507307-29a0d260-c7c7-49b8-8a90-490dd5bf3ea8.mp4

**Comment by poky** [comment]
> Here is a fully functional example of using LVGL 8.2 with LovyanGFX graphic library and PlatformIO, it is partially based on @uldara1's UI code.
> 
> https://github.com/strange-v/WT-86-32-3ZW1_LVGL
> 
>  WT-86-32-3ZW1_LVGL_.mp4

This repo works great!
Thanks for sharing!

**Comment by codewise-nicolas** [comment]
@shukewt is it closed because the files were added to the repo? I dont see them.
