### ISSUE TITLE
Display Not work with WT 86 32 3ZW1

### ISSUE THREAD

**Issue by uldara1** [wireless-tag-com/8ms-esp32#9]
Hello just try to use this module with arduino tft_espi
my config as below 
- after upload code lcd not display anything just only backlight 
- pls check my configure is correct ?

`#define TFT_PARALLEL_8_BIT
// The ESP32 and TFT the pins used for testing are:
#define TFT_CS -1  // Chip select control pin (library pulls permanently low
#define TFT_DC 38  // Data Command control pin - must use a pin in the range 0-31
#define TFT_RST 37 // Reset pin, toggles on startup

#define TFT_WR 39 // Write strobe control pin - must use a pin in the range 0-31
#define TFT_RD -1 // Read strobe control pin

#define TFT_D0 36 // Must use pins in the range 0-31 for the data bus
#define TFT_D1 35 // so a single register write sets/clears all bits.
#define TFT_D2 34 // Pins can be randomly assigned, this does not affect
#define TFT_D3 33 // TFT screen update performance.
#define TFT_D4 21
#define TFT_D5 18
#define TFT_D6 17
#define TFT_D7 16`

**Comment by fvanroie** [comment]
TFT_eSPI does not support this display/mcu combo yet.
You can try LovyanGFX instead which is confirmed working with the WT-86-32-3ZW1.

**Comment by shukewt** [comment]
We don't have support plan about arduino yet,you can check the pcb design for your IO configure
